=== Datzu/ZombieGame/res/scores.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/settings"
	xmlns:tns="http://www.example.org/settings" elementFormDefault="qualified">







    <element name="highScores" type="tns:highScores"></element>
    

    <complexType name="highScores">
    	<sequence>
    		<element name="player" type="tns:player" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <complexType name="player">
    	<sequence>
    		<element name="name" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="score" type="int" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>
</schema>

=== Datzu/ZombieGame/res/scores.xml
<?xml version="1.0" encoding="UTF-8"?>
<highScores xmlns="http://www.example.org/settings"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/settings scores.xsd ">
	<player>
		<name>Player 1</name>
		<score>1000</score>
	</player>
	<player>
		<name>Player 2</name>
		<score>500</score>
	</player>
	<player>
		<name>Player 3</name>
		<score>250</score>
	</player>
	<player>
		<name>Player 4</name>
		<score>200</score>
	</player>
</highScores>
